services:
  mysql:
    image: mariadb:latest
    platform: linux/amd64
    container_name: bank-mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=bankdb
      - MARIADB_USER=bankuser
      - MARIADB_PASSWORD=bankpass
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h localhost -u root -proot -e 'SELECT 1;'"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bank-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bankdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=bankuser
      - SPRING_DATASOURCE_PASSWORD=bankpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MariaDBDialect
    restart: always

networks:
  default:
    name: bank-network
    driver: bridge

volumes:
  mysql_data:
    name: bank_mysql_data
