[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "java -jar app.jar"
healthcheckPath = "/login.html"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
SPRING_PROFILES_ACTIVE = "prod" 